# Project: QUANLYSINHVIEN
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Main.o
LINKOBJ  = Main.o
LIBS     = -L"C:/Users/ASUS/Dev-Cpp/MinGW64/lib" -L"C:/Users/ASUS/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/ASUS/Dev-Cpp/MinGW64/include" -I"C:/Users/ASUS/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ASUS/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/ASUS/Dev-Cpp/MinGW64/include" -I"C:/Users/ASUS/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ASUS/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/ASUS/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = QUANLYSINHVIEN.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)
